name: Build JARVIS EXE
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller
      - name: Build EXE
        run: |
          pyinstaller --noconfirm --onefile --windowed --icon="assets/icons/jarvis.ico" --add-data "assets;assets" src/main.py
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: JARVIS-Windows-Build
          path: dist/main.exe
